<a href="https://colab.research.google.com/github/Prathima-tr/Problem-Solving-and-Programming/blob/main/Arrays_and_User_Defined_Data_Types_2022_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shared by Prof. Swamy Das, Dept. of CSE, CBIT

In [ ]:
#program to compute the length of a given string
s = input("Enter s string: ") # read a string
count = 0
for char in s: #loop on until the list is exhausted
  count += 1 # increment the count for each element
print("Length of the given string {} is: ", s, count)

Enter s string: cbit
Length of the given string {} is:  cbit 4


In [ ]:
## An array is a collection of items stored at contiguous memory locations. 
#In Python a list (Dynamic Array treated as an array)
##ways to create arrays

a = [] #creates an empty list
print("Empty array : ", a)
b = [0] * 10 #create a 1D array with size 10 and initializes with 0
print("\n1D array : ",b)

c = [None] * 10 #create a 1D array with size 10 and initializes with None
print("\nArray with None: ", c)

#creates a 2D (4x3) array with 3 columns and 4 rows and initializes the elements with 1
d = [[1] * 3] * 4

##direct dispaly
print("\n2D array : ", d)

#printing the matrix with loops
print("2D array displayed with loops:")
for i in range(len(d)):
  for j in range(len(d[0])):
    print(d[i][j], end=" ")

print()

#creates an arrray and initializes with the i value
arr = [] #create an empty list - 1D
for i in range(10):
  arr.append(i) #append i value in each iteration
print("\nArray created with append(): ", a)

## creating arrays with iterator
a1 = [0 for i in range(10)] #create 1D array and initialize each element with 0
print("\n1D array created with iterator with 0 values: ",a1)

a2 = [None for i in range(10)] #create 1D array and initialize each element with None
print("\n1D array created with iterator with None: ",a2)

Empty array :  []

1D array :  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Array with None:  [None, None, None, None, None, None, None, None, None, None]

2D array :  [[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
2D array displayed with loops:
1 1 1 1 1 1 1 1 1 1 1 1 

Array created with append():  []

1D array created with iterator with 0 values:  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

1D array created with iterator with None:  [None, None, None, None, None, None, None, None, None, None]


In [ ]:
#Repetition operator on a nested list
#Items in the sequences are not copied, they are referenced multiple times.
l1=[[2]]
l2=l1*2
#Elements in list l2 are referring to the same element in list l1. 
#So, modifying any of the elements of list l1 will modify list l2 as well.
l1=[[2]]
l2=l1*2
print ("L2 is ", l2, "id  of L2 is ",id(l2))#Output:[[2], [2]]
l1[0][0]=99
print ("L1 is ", l1, "\tid  of L1 is ",id(l1))#Output:[[99]]
print ("L2 is ", l2, "id  of L2 is ",id(l2))#Output:[[99], [99]]

In [ ]:
#Repetition operator on a nested tuple

t1=((2,))
t2=t1*2

t1=((2,))
t2=t1*2
print ("t2 is ", t2, "id  of t2 is ",id(t2))
print ("t1 is ", t1, "  id  of t1 is ",id(t1))
print ("t2 is ", t2, "id  of t2 is ",id(t2))


In [ ]:
## creating arrays with iterator
a1 = [i**2 for i in range(2,10,3)] #create 1D array and initialize each element with 0
print("\n1D array created with iterator with 0 values: ",a1)


1D array created with iterator with 0 values:  [4, 25, 64]


In [ ]:
d = [[1] * 3] * 4
print(d)

[[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]


In [ ]:
## arrays using Numpy
import numpy as np
# create a simple array with Numpy
a = np.empty(10, dtype=object)
print(a)
# create multi-dimensional array by providing shape
matrix = np.empty(shape=(3, 4), dtype='object')
print(matrix)
print(type(a),type(matrix))

[None None None None None None None None None None]
[[None None None None]
 [None None None None]
 [None None None None]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
##program to add two vectors
v1 = [10,20,30,40] #create a vector V1 with the values of 10, 20, 30, and 40
v2 = [11,12,13,14] #create a vector V2 with the values of 11, 12, 13, and 14

v = [0 for i in range(4)] #create a vector V and initialize with 0

## print(v1+v2) #concatenates
for i in range(len(v1)):
  v[i] = v1[i] + v2[i] #adds with the respective values in V1 and V2

print(v1)
print(v2)
print(v)

[10, 20, 30, 40]
[11, 12, 13, 14]
[21, 32, 43, 54]


In [ ]:
## 2D Arrays/matrices Method - 1
m1 = [[1,2,3], [4,5,6], [7,8,9], [0, -1, 2]] #initialize matrix 1
m2 = [[5,6,7], [1,2,3], [7,8,9], [1, 4, 2]] #initialize matrix 2
print("Matrix 1: ", m1)
print("Matrix 2: ", m2)

#print(m1+m2) #concatenates the elements in both matrices
m3 = [[0,0,0], [0,0,0], [0,0,0], [0,0,0]]
print("Matrix 3: ",m3) #display the matrix

#addition
for i in range(len(m1)): # iterate through rows
  for j in range(len(m1[i])): # iterate through columns
    m3[i][j] = m1[i][j] + m2[i][j] # add the respective elements
print("Resultant:", m3)

#printing the matirx with one loop
for i in range(len(m3)): #print one row at a time
  print(m3[i])
print()

#printing the matrix with two loops
for i in range(len(m3)):
  for j in range(len(m1[1])): #for each row, create for all columns
    print(m3[i][j], end=" ") #print one element at a time
  print()

Matrix 1:  [[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, -1, 2]]
Matrix 2:  [[5, 6, 7], [1, 2, 3], [7, 8, 9], [1, 4, 2]]
Matrix 3:  [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
Resultant: [[6, 8, 10], [5, 7, 9], [14, 16, 18], [1, 3, 4]]
[6, 8, 10]
[5, 7, 9]
[14, 16, 18]
[1, 3, 4]

10 9 18 
10 9 18 
10 9 18 
10 9 18 


In [5]:
##Matrix Addition Method-2
#use of nested loop to iterate through each row and column. 
#At each point add  the corresponding elements and store in Result
m1 = [[1,2,3], [4,5,6], [7,8,9], [0, -1, 2]]
m2 = [[5,6,7], [1,2,3], [7,8,9], [1, 4, 2]]
print("Matrix 1: ", m1)
print("Matrix 2: ", m2)

#print("m1+m2",m1+m2)

#m3 = [[None,None,None], [None,None,None], [None,None,None], [None,None,None]]

#addition
result = [[m1[i][j] +m2[i][j] for j in range(len(m1[0]))] for i in range(len(m1))]
print("Result is:", result)
print()

for i in result:
  print(i)

Matrix 1:  [[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, -1, 2]]
Matrix 2:  [[5, 6, 7], [1, 2, 3], [7, 8, 9], [1, 4, 2]]
Result is: [[6, 8, 10], [5, 7, 9], [14, 16, 18], [1, 3, 4]]

[6, 8, 10]
[5, 7, 9]
[14, 16, 18]
[1, 3, 4]


In [6]:
##Matrix addition Method - 3
import numpy as np
m1 = [[1,2,3], [4,5,6], [7,8,9], [0, -1, 2]]
m2 = [[5,6,7], [1,2,3], [7,8,9], [1, 4, 2]]
print("Matrix 1: ", m1)
print("Matrix 2: ", m2)
result = np.array(m1) + np.array(m2)
print(result)

Matrix 1:  [[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, -1, 2]]
Matrix 2:  [[5, 6, 7], [1, 2, 3], [7, 8, 9], [1, 4, 2]]
[[ 6  8 10]
 [ 5  7  9]
 [14 16 18]
 [ 1  3  4]]


In [7]:
## Matrix addition Method - 4 use of sympy library
from sympy import Matrix
m1 = [[1,2,3], [4,5,6], [7,8,9], [0, -1, 2]]
m2 = [[5,6,7], [1,2,3], [7,8,9], [1, 4, 2]]
mat_x = Matrix(m1)
mat_y = Matrix(m2)
print("Matrix 1: ", m1)
print("Matrix 2: ", m2)
result = mat_x + mat_y
print(result)
for i in range(len(m1)):
  for j in range(len(m1[0])):
    print(m1[i][j], end=" ")
print()

Matrix 1:  [[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, -1, 2]]
Matrix 2:  [[5, 6, 7], [1, 2, 3], [7, 8, 9], [1, 4, 2]]
Matrix([[6, 8, 10], [5, 7, 9], [14, 16, 18], [1, 3, 4]])
1 2 3 4 5 6 7 8 9 0 -1 2 


In [ ]:
## Matrix Addition
# Method - 4. use of nested list comprehension to iterate through each element in the matrix.
# List comprehension allows to write concise codes and must try to use them frequently in Python.
# zip() function accepts iterator i of each element (list) of matrix, mapping 
#them, adding them using sum and storing them in map form
m1 = [[1,2,3], [4,5,6], [7,8,9], [0, -1, 2]]
m2 = [[5,6,7], [1,2,3], [7,8,9], [1, 4, 2]]
print("Matrix 1: ", m1)
print("Matrix 2: ", m2)
result = [map(sum, zip(*t)) for t in zip(m1,m2)]
print("Result: ", result)

In [8]:
#### Write a Python program to find the largest number from a given list of elements.
## array as a list
n =int(input("How many numbers: "))
l = []
max = -9999
print("Enter the Numbers:")
for i in range(n):
  a = int(input("Enter the next item: "))
  l.append(a)
  if a>max:
    max = a
print("Given list: ",l)
print("Largest is: ", max)

How many numbers: 5
Enter the Numbers:
Enter the next item: 12
Enter the next item: 45
Enter the next item: -9
Enter the next item: 23
Enter the next item: 67
Given list:  [12, 45, -9, 23, 67]
Largest is:  67


In [ ]:
## linear search version 1
import array as ar
n=int(input("How many numbers: ")) # Read the size of list
a=ar.array('i',[0 for i in range(n)]) #create an array with 'n' zeros

print("Enter ",n, "elements: ")
for i in range(len(a)): # loop to get 'n' elements
  a[i]=int(input())

x=int(input("Enter the element to be searched: "))
print("Given elements: ", a)
flag=0 #set the flag to 0, assuming the  element is not there in the list
for i in a: #iterate the loop until 'x' is found or the list exhausted
  if x==i:
    flag=1 # if found, set the flag to 1 and break the loop
    break
if flag==1:
  print(x, "is there in the list.......")
else:
  print(x, "is NOT there in the list !!!!!!!!!!!")

In [ ]:
## linear search version 2
import array as ar
n=int(input("How many numbers: "))
a=ar.array('i',[0 for i in range(n)]) #create an array with 'n' zeros
print("Enter ",n, "elements: ")
for i in range(len(a)):
  a[i]=int(input())

x=int(input("Enter the element to be searched: "))
print("Given elements: ", a)
flag=0
for i in range(len(a)):
  if a[i]==x:
    flag=1
    break
if flag==1:
  print(x, "is there in the list at position ", i)
else:
  print(x, "is NOT there in the list !!!!!!!!!!!")

In [ ]:
## linear search version 3
import array as ar

n=int(input("How many numbers: ")) # Read the size of list
a=ar.array('i',[0 for i in range(n)]) #create an array with 'n' zeros
print("Enter ",n, "elements: ")

for i in range(len(a)): #loop to read n elements
  a[i]=int(input())

x=int(input("Enter the element to be searched: "))
print("Given elements: ", a)
flag=0

if x in a: # 'in' operator here searches the list for x. If found it returs TRUE
  print(x, "is there in the list.......")
else:
  print(x, "is NOT there in the list !!!!!!!!")

In [ ]:
## linear search version 4
## using a function
import array as ar
def linear_search(a,n,x): # function definition
  for i in range(n):
    if a[i] == x: # check whether 'x' is there in the list
      return i # return the position 'i' if 'x' is found
  return -1 # function returns -1 if the list is exhausted

n=int(input("How many numbers: "))
a=ar.array('i',[0 for i in range(n)]) #create an array with 'n' zeros
print("Enter ",n, "elements: ")

for i in range(len(a)): #read n elements
  a[i]=int(input())

x=int(input("Enter the element to be searched: "))
print("Given elements: ", a)

s = linear_search(a,n,x) #call the function linear_search()

if (s!=-1): #if the value retured by the function call is not -1 ,print 'x' is at position 's'
  print(x, "is there in the list at position ",s)
else:
  print(x, "is NOT there in the list !!!!!!!!!!!")

In [ ]:
##binary search
n =int(input("How many elements: "))
a=[0]*n
print("Enter ", n, "numbers: ")
for i in range(n): #read 'n' elements from the user
  a[i] = int(input())

x= int(input("Enter the element to be searched: "))
low = 0
high = n-1
found = 0
while (low <= high): #repeat until the lower bound exceeds of item is found
  mid = (low +high)//2 # find the middle position
  if(a[mid] == x): # if the middle element is 'x' then terminate the loop by changing the found as 1
    found = 1
    break
  elif a[mid] < x: # if middle element is less than 'x', then change the lower bound to mid+1
    low = mid +1
  else: # if midle element is greater than 'x' then change the upper bound to mid-1
    high = mid-1
print("Given list is: ", a)

if (found == 1): #if the loop terminated by changing the found value a 1, then the element is there
  print(x, "is there in the list at ", mid)
else:
  print(x, "is NOT there in the list")
## Write a Python program to count the number of

In [ ]:
## Write a Python program to count the number of characters (character frequency) in a string.
arr=input("Enter a string:")
fr = [0]*len(arr) #create a frequency vector of size 'arr' and 
initialize with 0
visited = -1;
for i in range(len(arr)):
  count=1
for j in range(i+1, len(arr)):
  if(arr[i] == arr[j]):
    count = count +1 #To avoid counting same element again
    fr[j] = visited
    if(fr[i] == visited):
      fr[i] = count
#Displays the frequency of each element present in array
print(fr)
print("---------------------");
print("|Element | Frequency|");
print("---------------------");

for i in range(0, len(fr)):
  if (fr[i] != visited):
print("|",arr[i], " | ", fr[i], " |")
print("---------------------")

In [ ]:
def add_string(str1):
  length = len(str1)
  if length > 2:
    if str1[-3:] == 'ing':
      str1 += 'ly'
    else:
      str1 += 'ing'
  return str1

print(add_string('ab'))
print(add_string('abc'))
print(add_string('string'))

In [ ]:
def word_count(str):
  counts = dict()
  words = str.split()
  for word in words:
    if word in counts:
      counts[word] += 1
    else:
      counts[word] = 1
  return counts

print(word_count("Chaitanya Bharathi Chaitanya Bharathi Hyderabad, Gandipt."))

In [ ]:
##build a substring with the characters at even positions
str= input("Enter a string: ")
result=""
for i in range(len(str)):
  if i%2==0:
    result = result + str[i]

print("Geven string: ", str)
print("New string:", result)

In [ ]:
##Matrix addition using lists
a=[] #construction of matrix A
for i in range(5):
  r=[]
  for j in range(4):
    r.append(i)
  a.append(r)
print("\nMatrix A: ")

for i in range(5):
  print(a[i])

b=[] #construction of matrix B
for i in range(5):
  r=[]
  for j in range(4):
    r.append(i)
b.append(r)
print("\nMatrix B: ")
for i in range(5):
  print(b[i])

c=[] #construction of matrix C by adding A and B
for i in range(5):
  r=[]
  for j in range(4):
    r.append(a[i][j]+b[i][j])
  c.append(r)
print("\nResultant matrix: ")

for i in range(5):
  for j in range(4):
    print(c[i][j], end=" ")

print("")

In [ ]:
##User defined data types
#Linked List
llist = ['1. CBIT', '2. MGIT', '3. Vasavi ']
print(llist)
# print(id(llist[0]), id(llist[1]), id(llist[2]))

## adding elements
llist.append('4. OUCE ')
llist.append('5. MVSR')
llist.insert(3, '6. JNTUH')
print(llist)
#print(id(llist[0]), id(llist[1]), id(llist[2]), id(llist[3]), id(llist[4]),  id(llist[5]))
#print(id(llist[2]))
llist.remove('6. JNTUH')
print(llist)
#print(id(llist[0]), id(llist[1]), id(llist[2]), id(llist[3]), id(llist[4]))
print()

In [ ]:
##Stack
stack = ['CBIT', 'MGIT', 'OUCE']
print("Stack elements: ", stack)

# pushing elements
stack.append('VASAVI')
stack.append('MVSREC')
print("Stack after 2 pushes: ", stack)

# printing top
n = len(stack)
print("Top element: ", stack[n-1])
print()

# popping element
stack.pop()
print("Stack after pop(): ", stack)

In [ ]:
## Queues
queue = ['CBIT', 'MGIT', 'OUCE']
print("Queue: ", queue)

# pushing elements
queue.append('MVSR')
queue.append('JNTUH')

print("Queue after inserting two elements: ", queue)
# printing head
print("1st element: ", queue[0])
# printing tail
n = len(queue)
print("Last element in the queue: ", queue[n-1])
# popping element
queue.remove(queue[0])
print("Queue after remove operation: ", queue)

In [ ]:
def printdict(d):
  for key in d:
    print(key, "->", d[key])

hm = {1: 'CBIT', 2:'MGIT', 3:'VASAVI'}

printdict(hm)
print()

hm[3] = "OUCE"
printdict(hm)
print()

hm.popitem()
printdict(hm)

In [ ]:
hrs = int(input("Enter the browsing hours: "))
mts = int(input("Enter the browsing minutes: "))
mhrs = hrs // 5 # multiples of 5 hours
rhr= hrs % 5 # remaing hours
Bill = mhrs * 200 + rhr * 50 + mts * 1
print("Total bill amount: ", Bill)
##as per your interpretation this will work correctly up to the hours is less than 10
if (hrs > 5):
  bill = 200 + (hrs-5) * 50 + mts * 1
elif (hrs<5 and hrs>1):
  bill = hrs * 50 + mts *1
else:
  bill = mts *1
print("Bill amount: ", bill)

In [ ]:
# Program to check Armstrong numbers in a certain interval i.e. 1 to 2000
lower = 1
upper = 2000
for num in range(lower, upper + 1): #take a number
  temp = num
  order = 0
  while temp: #compute the length of the number
    temp = temp//10
    order = order + 1

  #print("order of", num)
  sum = 0 # initialize sum
  temp = num
  while temp:
    digit = temp % 10
    sum += digit ** order #add the digit raised to the power of the number of digits in a given number

  #print(digit, end=" ")
  temp = temp // 10
  if (sum == num):
    print(num, end = " ")

In [ ]:
##Graphs
class node:
    def __init__(self, ele):
      self.ele = ele
      self.left = None
      self.right= None

def preorder(self):
  if self:
    print(self.ele)
    preorder(self.left)
    preorder(self.right)

n = node('first')
n.left = node('second')
n.right = node('third')

preorder(n)