Done by Umadevi (RNo:16) 2022-23 Batch, AI&DS, Section-1
Course: PSP Lab (22csc02)

> Indented block



NOT DONE YET: Q21(a),Q22(a),Q26(a)







In [ ]:
# Q1 Write a python program to explain the scope of local and global variables using functions

global_var=23
def fun1():
  global_var=15
  print('The value of global_var in fun1 :',global_var)

def fun2():
  local_var=19
  print('The value of local_var in fun2 :',local_var)

print('THe value of global_var defined outside : ',global_var)
(fun1())
fun2()
#print(local_var)           # throws an error as local_var is not defined outside the fun2.....not globally defined

THe value of global_var defined outside :  23
The value of global_var in fun1 : 15
The value of local_var in fun2 : 19


In [ ]:
# Write a python program to merge the contents of two files into one file
# 1st file
f1=open('my_file1','wt')
f1.write('This is my first file\n')
f1.write('2nd ine of my 1st file\n')


#2nd file

f2=open('my_file2','wt')
f2.write('This is second file\n')
f2.write('2nd line of my 2nd file\n')



#new file
# copying file 1 and2 into 3
f3=open('newfile','wt')
f1=open('my_file1','rt')
f2=open('my_file2','rt')
a=f1.read()
b=f2.read()
f3.write(a)
f3.write(b)

## reading the contents of3rd file i.e merged file
f3=open('newfile','rt')
r3=f3.read()

print('first file----- : ',a)
print('second file----- : ',b)
print('3rd file------ : ',r3)

first file----- :  This is my first file
2nd ine of my 1st file

second file----- :  This is second file
2nd line of my 2nd file

3rd file------ :  This is my first file
2nd ine of my 1st file
This is second file
2nd line of my 2nd file



In [ ]:
##  Q2. Illustrate different read functions available in files

f11=open('my_files','wt')
f11.write('Hi this is Umadevi\n')
f11.write('Nice to meet you\n')
f11.write('lets catch up later\n')
f11.close()

fo=open('my_files','rt')
# .read()
a=fo.read()
print('WIth read()------:',a)

fo=open('my_files','rt')
#readline()
b=fo.readline(100)
b1=fo.readline(200000000)
print('With readline---: ',b,'next line     : ',b1)

fo=open('my_files','rt')
# readlines()
c=fo.readlines()
print('with readlines-----: ',c)
fo.close()
print()

fo.closed

WIth read()------: Hi this is Umadevi
Nice to meet you
lets catch up later

With readline---:  Hi this is Umadevi
 next line     :  Nice to meet you

with readlines-----:  ['Hi this is Umadevi\n', 'Nice to meet you\n', 'lets catch up later\n']



True

In [ ]:
# Find the sum of odd factors of a given number

n=int(input())
i=1
sum=0
while i<=n:
  if n%i==0 and i%2!=0:
    sum+=i
  i+=1
print('sum of odd factors is :',sum)


20
sum of odd factors is : 6


In [ ]:
# 3. Illustrate different write functions available in files

fo=open('my_file','wt')
# .write(str): a single line is written
fo.write('HI all\n ')
# writelines(list): write multiple lines into a file. each string of the list is a new line
fo.writelines(['Goodmorning\n','Good afternoon\n','Good evening\n'])
fo.close()

fo1=open('my_file','rt')
a=fo1.read()
print(a) 

HI all
 Goodmorning
Good afternoon
Good evening



In [ ]:
#Find the sum of all elements of a 2D array

a=[[1,2,3],
   [4,6],
   [7,8,9]]

sum=0
for i in range(len(a)):
  for j in range(len(a[i])):
    sum+=a[i][j]
print(sum)

40


In [ ]:
# 4. Find whether a number is Armstrong 

n=int(input())
sum=0
x=n
while n>0:
  rem=0
  rem=n%10
  sum+=rem**3
  n=n//10

if sum==x:
  print('The number' ,x, 'is amstrong number')
else:
  print('The number',x,'is not amstrong number')



123
The number 123 is not amstrong number


In [ ]:
## Write a program to convert Celsius to Fahrenheit. F = (9/5) *C+32 using functions; C must be sent as argument 
#to function and inturn function should return the Fahrenheit to caller

def f(c):
  f=(9/5)*c+32
  print(f,'F')

c=float(input('Temperature in celsius '))
f(c)

Temperature in celsius 100
212.0 F


In [ ]:
# 5. Illustrate List: insertion, appending, removing, Indexing, Slicing, Mutability, predefined operations

my_list=[1,2,4,5,6,7,8,9]
# insertion
my_list.insert(2,3)
print('Inserted 3 at 2nd index:' ,my_list)
# appending
my_list.append(10)
print('THe list after appending 10 :',my_list)
# removing
my_list.remove(8)
print('The list after removing the elemnet 8:',my_list)
#Indexing
print('Indexing on list, element at 5th index :',my_list[5])
# slicing
print('slicing with step 3 from starting till end:',my_list[::3])
#Mutability
my_list[4]=20
print('The list after updating ',my_list)
### predefined operations
print('Length of the list:',len(my_list))
#repetion
print('List after repeating:' ,my_list*2)
my_list1=[11,12,13,14,15]
# concatination
print('concatination on lists:',my_list+my_list1)
# membership
print('Membership test:',14 in my_list)



Inserted 3 at 2nd index: [1, 2, 3, 4, 5, 6, 7, 8, 9]
THe list after appending 10 : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The list after removing the elemnet 8: [1, 2, 3, 4, 5, 6, 7, 9, 10]
Indexing on list, element at 5th index : 6
slicing with step 3 from starting till end: [1, 4, 7]
The list after updating  [1, 2, 3, 4, 20, 6, 7, 9, 10]
Length of the list: 9
List after repeating: [1, 2, 3, 4, 20, 6, 7, 9, 10, 1, 2, 3, 4, 20, 6, 7, 9, 10]
concatination on lists: [1, 2, 3, 4, 20, 6, 7, 9, 10, 11, 12, 13, 14, 15]
Membership test: False


In [ ]:
#Write a program in Python to compute GCD of given numbers using recursion

def gcd(a,b):
  if a%b==0:
    return b
  else:
    return gcd(b,a%b)
a=int(input())
b=int(input())
print('The gcd of',a,'and',b,'is:',gcd(a,b))


2
9
The gcd of 2 and 9 is: 1


In [ ]:
# 6. Illustrate Tuple: Indexing, Slicing, Immutability, predefined operations

t=(2,4,6,8,10)
# indexing
print('Indexing: ',t[3])
#slicing 
print('slicing: ',t[2:4])
# immutability
# tuple elements cannot be updated, order cannot be change
# predefined operations
# concatenation
t1=(1,2,3,4,5,6,7,8)
print('concatenation on tuples: ',t+t1)
# membership
print('membership test on tupe: ',4 in t)
# repeator
print('repetetion on tuples: ',t1*2)

Indexing:  8
slicing:  (6, 8)
concatenation on tuples:  (2, 4, 6, 8, 10, 1, 2, 3, 4, 5, 6, 7, 8)
membership test on tupe:  True
repetetion on tuples:  (1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8)


In [ ]:
# Q6 Write a program in Python to compute LCM of given numbers using recursion

def lcm(a,b):
  t=a%b
  if a%b==0:
    return a
  else:
    return a*lcm(b,a%b)/(a%b)

a=int(input())
b=int(input())
print("LCM of ",a,'and',b,'is:',lcm(a,b))

6
2
LCM of  6 and 2 is: 6


In [ ]:
# Q7 Illustrate Dictionary: insertion, appending, removing, Key, values, retrieving, predefined operations
d={1:'a',2:'b',3:'c',4:'d',5:'e'}
# insertion  appending
d[6]='f'
print('Dict after inserting new key value pair:',d)
# removing
d.pop(3)
print('THe dict after removing a key:',d)
# keys
print('Keys of the dict:',d.keys())
#values
print('Values of the dict:',d.values())
#retriving
print('Retriving:',d[2])
print('Keys and values of dict:',d.items())

Dict after inserting new key value pair: {1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f'}
THe dict after removing a key: {1: 'a', 2: 'b', 4: 'd', 5: 'e', 6: 'f'}
Keys of the dict: dict_keys([1, 2, 4, 5, 6])
Values of the dict: dict_values(['a', 'b', 'd', 'e', 'f'])
Retriving: b
Keys and values of dict: dict_items([(1, 'a'), (2, 'b'), (4, 'd'), (5, 'e'), (6, 'f')])


In [ ]:
#Find the factorial of a given number using iteration, return both no and the factorial to the caller

def fact(n):
  i=1
  nfact=1
  while i<=n:
    nfact*=i
    i+=1
  return nfact

n=int(input())
print('The factorial of',n,'is:',fact(n))

5
The factorial of 5 is: 120


In [ ]:
# 8. Illustrate String: Indexing, Slicing, Immutability, predefined operations

s='Umadeeevi'
print('indexing on string: ',s[4])
print('slicing on strings: ',s[1:6:2])
s2='Putta'
print('concatenation on strings: ',s+s2)
print('Membership test: ','e' in s)
print('repetetion on strings: ',s2*2)



#Find factorial of a given number using recursion

def rfact(n):
  if n<0:
    return None
  elif 0<=n<=1:
    return 1
  else:
    return n*rfact(n-1)

n=int(input())
print('The factorial of',n,'is :',rfact(n))

indexing on string:  e
slicing on strings:  mde
concatenation on strings:  UmadeeeviPutta
Membership test:  True
repetetion on strings:  PuttaPutta
5
The factorial of 5 is : 120


In [ ]:
#9. Write a program to find whether a string is palindrome

# false means the string is not palindrome
def p(s):
  l=0
  h=len(s)-1
  while l<h:
    if s[l]!=s[h]:
      return False
    l+=1
    h-=1
  return True

print(p('Telugu'))
print(p('malayalam'))

False
True


In [ ]:
# Demonstrate accumulation on a list

list1=[]
n=int(input('No. of elements to be appended in a list: '))
for i in range(n):
  i=int(input())
  list1.append(i)
sum=0
for j in list1:
  sum+=j
print('List accumulation: ',sum)

No. of elements to be appended in a list: 5
1
2
3
4
5
List accumulation:  15


In [ ]:
#10. Implement recursive Linear Search

def recursive_linear(arr,low,high,x):
  if low>high:
    return 'Not found'
  elif arr[low]==x:
    return low
  elif arr[high]==x:
    return  high
  else:
    return recursive_linear(arr,low+1,high-1,x)

arr=[2,3,5,6,72,34,5,688]
x=int(input('The elemnet to be searched : '))
print(recursive_linear(arr,0,len(arr)-1,x))

The elemnet to be searched : 654
Not found


In [ ]:
#Implement Matrix Addition create matrices using nested lists

m1=[[1,1,1],
    [2,2,2],
    [3,3,3]]

m2=[[3,3,3],
    [2,2,2],
    [1,1,1]]

result=[[0,0,0],
        [0,0,0],
        [0,0,0]]

for i in range(len(m1)):          # no. of rows of 1st matrix 1 or 2
  for j in range(len(m1[0])):     # no. of columns of matrix 1 or 2
    result[i][j]+=m1[i][j]+m2[i][j]

for row in result:
  print(row)

[4, 4, 4]
[4, 4, 4]
[4, 4, 4]


In [ ]:
# 11. Implement iterative Linear Search

def iterative_linear(arr,x):
  c=0
  for i in arr:
    if i==x:
      print('THe element is found ') 
      c+=1
  if c==0:
    print('The element is NOT FOUND')

arr=[2,3,5,6,7,8,21,3,43,4,5]
x=456
(iterative_linear(arr,x))

The element is NOT FOUND


In [ ]:
#Implement Matrix Multiplication

m1=[[1,1,1],
    [2,2,2],
    [3,3,3]]

m2=[[3,3,3],
    [2,2,2],
    [1,1,1]]

result=[[0,0,0],
        [0,0,0],
        [0,0,0]]

if len(m1[0])==len(m2):
  for i in range(len(m1)):
    for j in range(len(m2[i])):
      for k in range(len(m2)):
        result[i][j]+=m1[i][k]*m2[k][j]
else:
  print('matrix multiplication is not possible')

for row in result:
  print(row)

[6, 6, 6]
[12, 12, 12]
[18, 18, 18]


In [ ]:
# 12. Implement recursive Binary Search 

def recursive_binary(arr,low,high,x):
  if low>high:
    return 'Not found'
  else:
    mid=(low+high)//2
    if arr[mid]==x:
      return 'The element is found at index:',mid
    elif arr[mid]>x:
      return recursive_binary(arr,low,mid-1,x)
    else:
      return recursive_binary(arr,mid+1,high,x)

l=[2,4,6,7,8,9,12]
x=int(input())
print(recursive_binary(l,0,len(l)-1,x))

5
Not found


In [ ]:
#Illustrate the usage of tell() and seek() functions

f1=open('my_file1','wt')
f1.write('This is my first file\n')
f1.write('2nd ine of my 1st file\n')
f1.close()
f2=open('my_file1','r')
f2.read(10)
a=f2.tell()
print(a)
f2.seek(0,2)                 #By default from_what argument is set to 0. Note: Reference point at current position / end of file cannot be set in text mode except when offset is equal to 0.
b=f2.tell()
print(b)

10
45


In [ ]:
#13. Implement iterative Binary Search using functions

def iterative_binary(arr,x):
  low=0
  high=len(arr)-1
  mid=0
  while low<=high:
    mid=(low+high)//2
    if arr[mid]==x:
      return mid
    elif arr[mid]>x:
      high=mid-1
    else:
      low=mid+1
  return 'not found'
l=[2,4,6,7,8,9,12]
x=int(input())
print(iterative_binary(l,x))




12
6


In [ ]:
# Find nth Fibonacci number using recursion

def fib(n):
  if n<=0:
    return None
  elif 0<n<=2:
    return n-1
  else:
    return fib(n-1)+fib(n-2)

n=int(input())
print('The ',n,'fibinacci number is:',fib(n))

5
The  5 fibinacci number is: 3


In [ ]:
# 14. Implement Bubble Sort using functions

L=[10,8,4,12,6,16,2]
for i in range(len(L)-1):
  for j in range(len(L)-1-i):
    if L[j]>L[j+1]:
      L[j],L[j+1]=L[j+1],L[j]

print(L)

[2, 4, 6, 8, 10, 12, 16]


In [ ]:
def bubble_sort(arr):
  n=len(arr)
  for i in range(n-1):
    for j in range(n-1-i):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1]=arr[j+1],arr[j]
  return L
  

L=[10,8,4,12,6,16,2]
print('List that has been sort by bubble sort:',bubble_sort(L))

List that has been sort by bubble sort: [2, 4, 6, 8, 10, 12, 16]


In [ ]:
# Write a program in python to determine the unique words and their frequency in a given string

s=input('Given string : ')
d={}
s1=s.split()
for i in s1:
  if i not in d:
    d[i]=1
  else:
    d[i]+=1

print(d)

Given string : THis is great adn great and awesome
{'THis': 1, 'is': 1, 'great': 2, 'adn': 1, 'and': 1, 'awesome': 1}


In [ ]:
#15. Write a program to find the size of a text file

fn=input()
fo=open(fn,'rt')
fo.seek(-0,2)
a=fo.tell()
print('The size of the given text file is ',a,'bytes')

/content/umafile1.txt
The size of the given text file is  31 bytes


In [ ]:
# Implement Selection Sort using functions

def selection_sort(arr):
  n=len(arr)
  for i in range(n-1):
    for j in range(i+1,n):
      if arr[i]>arr[j]:
        arr[i],arr[j]=arr[j],arr[i]
  return L
L=[10,8,4,12,6,16,2]
print('List that has been sort by selection sort:',selection_sort(L))

List that has been sort by selection sort: [4, 6, 8, 10, 12, 16, 2]


In [ ]:
# 16. Write a program to read the contents of a file and count the unique characters

fn=input('File name : ')
fileObj=open(fn,'rt')
a=fileObj.read()
d={}
for i in a:
  if i not in d:
    d[i]=1
  else:
    d[i]+=1

print("The count of unique characters: ",d)

File name : /content/umafile1.txt
the count of unique characters:  {'T': 1, 'H': 1, 'I': 1, 'S': 1, ' ': 5, 'i': 3, 's': 1, 'u': 2, 'm': 2, 'a': 1, 'd': 1, 'e': 4, 'v': 1, '\n': 1, 'n': 1, 'c': 1, 't': 2, 'o': 1}


In [ ]:
# list accumulation
#refer above

In [ ]:
#17. Write a program to copy the contents source file to destination file line by line

fn1=input('Name of source file : ')
fn2=input('Name of the destination file : ')
fo1=open(fn1,'rt')
fo2=open(fn2,'wt')
a=fo1.readlines()
for line in a :
  fo2.write(line) 

fo1.close()
fo2.close()

## reading the destination file
f2=open(fn2,'rt')
b=f2.readlines()
for line in b:
  print(line)

Name of source file : /content/umafile1.txt
Name of the destination file : myyy
THIS is umadevi

nice to meet u


In [ ]:
##Build a dictionary with name and phone nos. Search whether a given mobile no. is present in the dictionary, it is 
# present display the mobile no and name otherwise report entry missing

d={}
while True:
  phone_number=int(input('Mobile number : '))
  name=input('Name of the person : ')
  d[phone_number]=name
  choice=input('Enter Y or N : ')
  if choice in ('Y','y'):
    continue
  else:
    break

search_number=int(input('Enter the number that has to be searched : '))
c=0
for key in d:
  if key==search_number:
    print(key,'      ',d[key])
    c+=1
if c==0:
  print('The entry is missing ')


Mobile number : 9876345678
Name of the person : p1
Enter Y or N : y
Mobile number : 9876521345
Name of the person : p2
Enter Y or N : n
Enter the number that has to be searched : 9876521345
contact
9876521345        p2


In [ ]:
# 18. Demonstrate positional arguments and key word arguments used in functions

# positional arguments
# no of parameters should be equal to no of arguments
def triple_sum(a,b):
  return (a+b)*3
print('Positional arguments: ',triple_sum(4,2))

# key word arguments:
def logic_fun(a,b,c):
  return a*3+b*2+c

print('Keyword arguments: ',logic_fun(b=3,a=2,c=1))

Positional arguments:  18
Keyword arguments:  13


In [ ]:
# Demonstrate Dictionary accumulation

s='Hey there coming back to the code:'
d={}
for i in s:
  if i in d:
    d[i]+=1
  else:
    d[i]=1

print(d)

{'H': 1, 'e': 5, 'y': 1, ' ': 6, 't': 3, 'h': 2, 'r': 1, 'c': 3, 'o': 3, 'm': 1, 'i': 1, 'n': 1, 'g': 1, 'b': 1, 'a': 1, 'k': 1, 'd': 1, ':': 1}


In [ ]:
# 19. Write the details of ‘n’ students into a .csv file. Details include RNo, Name, Branch, EAMCET rank

header=['Roll.no','Name','Branch','Eamcet rank']
import csv
with open('my_csvfile','wt') as file:
  csv_file=csv.writer(file)
  csv_file.writerow(header)
  n=int(input('No. of students details to be entered: '))
  for i in range(n):
    Roll=int(input('Roll.no of the student: '))
    Name=input('Name of the student: ')
    Branch=input('Branch,student belongs to: ')
    Eamcetrank=int(input('RAnk of the student: '))
    csv_file.writerow([Roll,Name,Branch,Eamcetrank])

# reading the csv file
with open('my_csvfile','rt') as rfile:
  csv_rfile=csv.reader(rfile)
  for row in csv_rfile:
    print(row)
9

No. of students details to be entered: 2
Roll.no of the student: 016
Name of the student: Uma
Branch,student belongs to: aids
RAnk of the student: 4427
Roll.no of the student: 017
Name of the student: tej
Branch,student belongs to: aids
RAnk of the student: 2345
['Roll.no', 'Name', 'Branch', 'Eamcet rank']
['16', 'Uma', 'aids', '4427']
['17', 'tej', 'aids', '2345']


In [ ]:
#Write a function to read ‘n’ elements and return minimum, maximum and average of the list of elements.

L=[]
n=int(input('No. of elements: '))
for i in range(n):
  i=int(input())
  L.append(i)
print('THe list: ',L)
# sorting the list:
for j in range(len(L)-1):
  for k in range(j+1,len(L)):
    if L[j]>L[k]:
      L[j],L[k]=L[k],L[j]
print('list L after sorting : ',L)
print('The minimum is : ',L[0])
print('The maximun is : ',L[len(L)-1])
# finding average:
sum=0
for x in L:
  sum+=x
average=sum/len(L)
print('Average of list elements is :',average)

No. of elements: 5
2
10
8
4
6
THe list:  [2, 10, 8, 4, 6]
list L after sorting :  [2, 4, 6, 8, 10]
The minimum is :  2
The maximun is :  10
Average of list elements is : 6.0


In [ ]:
##Write a function to read ‘n’ elements and return minimum, maximum and average of the list of elements.

def min_max_avg(arr):
  return ('min is: ',min(arr)),('Maximum is :',max(arr)),('Average is : ',sum(arr)/len(arr))

L=[]
n=int(input('NO of. elements to be added in list: '))
for i in range(n):
  i=int(input())
  L.append(i)
print(min_max_avg(L))

NO of. elements to be added in list: 3
23
16
6
(('min is: ', 6), ('Maximum is :', 23), ('Average is : ', 15.0))


In [ ]:
# 20. Write a program to reverse the number using . Input: 123 output: 321; i/p:4534 o/p: 4354

n=int(input('Enter the number: '))
reverse=0
while n>0:
  rem=0 
  rem=n%10
  reverse=reverse*10+rem
  n=n//10
print('The reverse of the input is : ',reverse)
  


Enter the number: 4534
The reverse of the input is :  4354


In [ ]:
#Write a program to display the below pattern, for n=4:
#1 2 3 4
#1 2 3
#1 2
#1

n=int(input())
for i in range(1,n+1):
  for j in range(1,n+2-i):
    print(j,end='')
  print()

4
1234
123
12
1


In [ ]:
# 21 Illustrate math: sqrt(), ceil(), floor(), pow(), fabs(), sin(), cos(), tan()

import math
print('finding sqaure root: ',math.sqrt(81))
print('ceiling of a float: ',math.ceil(4.5))
print('floor of a real number: ',math.floor(4.5))
print('power : ',math.pow(2,3))
print('absolute of a number : ',math.fabs(-345))
print('sine of an angle: ',math.sin(math.pi/180*30))
print('cosine of an angle: ',math.cos(math.pi/180*30))
print('tangent of an angle: ',math.tan(math.pi/180*45))

finding sqaure root:  9.0
ceiling of a float:  5
floor of a real number:  4
power :  8.0
absolute of a number :  345.0
sine of an angle:  0.49999999999999994
cosine of an angle:  0.8660254037844387
tangent of an angle:  0.9999999999999999


In [ ]:
# 22 Illustrate Identity Operators

a=20
b=60
c='Hi'
d=20
# is operator
print('IS OPERATOR :')
print(a is b)
print(c is d)
print(a is d)
# is not operator
print('IS NOT OPERATOR:')
print(a is not b)
print(d is not d)
print(a is not d)

IS OPERATOR :
False
False
True
IS NOT OPERATOR:
True
False
False


In [ ]:
#23. Write a Python Program to find sum of digits of a positive number

n=int(input())
sum=0
while n>0:
  rem=0
  rem=n%10
  sum+=rem
  n=n//10
print('The sum of the digits of the given number is : ',sum)

1234
The sum of the digits of the given number is :  10


In [ ]:
#Illustrate membership operators
L=[2,3,4,1,23]
t=(2,4,7,8,9)
d={2:'a',4:'b',5:'c'}
# member ship test
# in operator
print('in OPERATOR')
print('for list: ',3 in L)
print('For tuple :',4 in t)
print('for dict: ',5 in d)
# not in operator
print('not in OPERATOR')
print('for list: ',9 not in L)
print('For tuple :',4 not in t)
print('for dict: ',5 not in d)

in OPERATOR
for list:  True
For tuple : True
for dict:  True
not in OPERATOR
for list:  True
For tuple : False
for dict:  False


In [ ]:
#24. Write a program to reverse the number. Input: 123 output: 321
#REFER ABOVE

In [ ]:
#Write a program in Python to find smallest of three nos
n1=int(input())
n2=int(input())
n3=int(input())
if n1<n2 and n1<n3:
  print(n1,'is the smallest ')
elif n2<n3:
  print(n2,'is the samllest')
else:
  print(n3,'is the smallest')


6
8
2
2 is the smallest


In [ ]:
#25. Write a program to find whether a no. is prime or not

n=int(input())
i=1
nof=0
while i<=n//2:
  if n%i==0:
    nof+=1
  i+=1
if nof<=1:
  print(n,'is a prime number')
else:
  print(n,'is not a prime number')


101
101 is a prime number


In [ ]:
#Illustrate statistics: mean(), median(), mode(), pstdev(), pvariabce(), stdev(), variance()

import statistics 
# mean()
print('Mean of the data: ',statistics.mean([9,8,7,6,5,4,3,2,1]))
# median
print('median of the data: ',statistics.median([2,4,6,8,10,14]))
#mode
print('Mode of the data: ',statistics.mode([2,3,4,5,6,7,8,2,3,3,2]))
# pstdev() : popultion standard deviation of data
print('popultion standard deviation of data: ',statistics.pstdev([4,6,1,3,8,9,10,10,90]))
#pvariance
print('population variance of the data: ',statistics.pvariance([2,9,8,9,70,60,5,0,50,40]))
#stdev()
print('sample standard deviation of data: ',statistics.stdev([10,20,30,40,50,60]))
#variance()
print('sample variance of data: ',statistics.variance([1,3,5,7,9,11,13,15,17,19,21]))

Mean of the data:  5
median of the data:  7.0
Mode of the data:  2
popultion standard deviation of data:  26.453313172035326
population variance of the data:  645.4100000000001
sample standard deviation of data:  18.708286933869708
sample variance of data:  44


In [ ]:
# 26 Illustrate random: random(), randint(), randrange()

import random
print('returns next random floating point in the range(0.0,1.0)',random.random())
print('returns random itegers : ',random.randint(23,32))
print('Random elemnt: ',random.randrange(200,1000,200))

returns next random floating point in the range(0.0,1.0) 0.5378870535114082
returns random itegers :  26
Random elemnt:  600


In [ ]:
#27. Write a program to find roots of a quadratic equation

# quadratic equation of the form ax^2+bx+c
import math
a=int(input())
b=int(input())
c=int(input())
d=b**2-4*a*c
x1=(-b+math.sqrt(d))/(2*a)
x2=(-b-math.sqrt(d))/(2*a)
print('The roots of the quadratic equation are {} and {}'.format(x1,x2))

1
-1
-12
The roots of the quadratic equation are 4.0 and -3.0


In [ ]:
#Write a program to display the below pattern, when n=4
#4 3 2 1
#4 3 2
#4 3
#4

n=int(input())
for i in range(1,n+1):
  j=n
  while j>=i:
    print(j,end=' ')
    j-=1
  print()

4
4 3 2 1 
4 3 2 
4 3 
4 


In [ ]:
#28. Write a Python Program to find whether a number is Perfect Number

n=int(input())
i=1
sum=0
while i<=n/2:
  if n%i==0:
    sum+=i
  i+=1
print('The sum of factors: ',sum)
if sum==n:
  print(n,'is a perfect number')
else:
  print(n,'is not a perfect number')

28
The sum of factors:  28
28 is a perfect number


In [ ]:
from six import binary_type
#Illustrate relational and bitwise operators

# relational operators
print('Greater than: ',5>2)
print('Greater than or equal to: ',20>=9)
print('Less than:  ',54<0)
print('less than or equal to: ',5<=6)
print('Equal to: ',5==3)
print('Not equal to:  ',2!=5)

#bitwise operators
x=6
y=10
print('bitwise AND: ',x&y)
print('bitwise OR: ',x|y)
print('bitwise XOR: ',x^y)
print('bitwise NOT: ',~x)
print('bitwise right shift :',x>>y)
print('bitwise leftshift :',x<<y)

Greater than:  True
Greater than or equal to:  True
Less than:   False
less than or equal to:  True
Equal to:  False
Not equal to:   True
bitwise AND:  2
bitwise OR:  14
bitwise XOR:  12
bitwise NOT:  -7
bitwise right shift : 0
bitwise leftshift : 6144


In [ ]:
#29. The program should display a message indicating whether the person is an infant, a child, a teenager, or an adult. 
#Following are the guidelines: If the person is 1 year old or less, he or she is an infant; If the person is older than 1 
#year, but younger than 13 years, he or she is a child; If the person is at least 13 years old, but less than 20 years 
#old, he or she is a teenager; If the person is at least 20 years old, he or she is an adult.


age=int(input())
if age>=20:
  print('The person is adult')
elif 13<=age<20:
  print('The person is teenager')
elif 1<age<13:
  print('The person is child')
else :
  print('Its infant')


6
The person is child


In [ ]:
# 30. Write a Python Program to find whether year is a leap year or not
y=int(input())
if y%4==0 and y%100!=0:
  print(y,'is a leap year')
elif y%400==0:
  print(y,'is a leap year')
else:
  print(y,'is not a leap year')

2016
2016 is a leap year


In [ ]:
#31. Write a program to print a multiplication table for a given ‘n’
table=int(input())
n=int(input())
m=int(input())
while n<m:
  result=table*n
  print(table,'* {} = {}'.format(n,result))
  n+=1

3
2
16
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30
3 * 11 = 33
3 * 12 = 36
3 * 13 = 39
3 * 14 = 42
3 * 15 = 45


In [ ]:
# 32. Write a Python Program to find whether year is a leap year or not
#Illustrate statistics: mean(), median(), mode(), pstdev(), pvariabce(), stdev(), variance()
# check above

In [ ]:
#33. Demonstrate the usage of break, continue and pass


In [ ]:
# 33Write a program to display the below pattern, for n=4:
#1 
#1 2 
#1 2 3
#1 2 3 4

n=4
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=' ')
  print('\n')

1 

1 2 

1 2 3 

1 2 3 4 



In [ ]:
# 34. Write a program to demonstrate + and * operators on top of sequences


#You can concatenate sequences of the same type with the + operator.
 #You can multiply a sequence S by an integer n with the * operator.
 # S * n or n * S is the concatenation of n copies of S . 

L1=[3,5,2,6,7,4,3]
L2=[2,3,4,8,0,1,8,2]
print('concatenation of two lists: ',L1+L2)
s='Uma'
s1='Devi'
print('concatenation on two strings: ',s+s1)

print('Repeation on lits: ',L1*2)
print('Repeation on strings: ',s*3)
d={1:'a',2:'b',3:'c'}
d2={4:'d',5:'e',2:'s'}
print('concatenation on dictionaries: ',{**d,**d2})

concatenation of two lists:  [3, 5, 2, 6, 7, 4, 3, 2, 3, 4, 8, 0, 1, 8, 2]
concatenation on two strings:  UmaDevi
Repeation on lits:  [3, 5, 2, 6, 7, 4, 3, 3, 5, 2, 6, 7, 4, 3]
Repeation on strings:  UmaUmaUma
concatenation on dictionaries:  {1: 'a', 2: 's', 3: 'c', 4: 'd', 5: 'e'}


In [ ]:
# Perform 2D matrix addition; create matrices using functions of Numpy 

# Arrays are a fundamental data structure, and an important part of most programming languages.
#In Python, they are containers which are able to store more than one item at the same time.
import numpy as np
# creating numpy arrays
m1=np.array([1,3,5,7,9,11])     # enclose in a list
print('1D array using numpy: ',m1)   
## creating 2D arrays
m2=np.array([[1,2,3],[4,5,6]])  # enclose in a list
print('2D array(matrix) using numpy : ')
print(m2)


# addition of matrices
mat1=np.array([[1,2,3],[6,5,4]])
mat2=np.array([[4,5,6],[3,2,1]])
print('ADDITION:')
print(np.add(mat1,mat2))
print('SUBTRACTION:')
print(np.subtract(mat1,mat2))

1D array using numpy:  [ 1  3  5  7  9 11]
2D array(matrix) using numpy : 
[[1 2 3]
 [4 5 6]]
ADDITION:
[[5 7 9]
 [9 7 5]]
SUBTRACTION:
[[-3 -3 -3]
 [ 3  3  3]]
